version: '3.1'

services:
  app:
    build:
      context: ./docker/php-fpm
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: cms-app
    networks:
      - cms-web_default
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    user: ${UID}:${GID}

  webserver:
    image: nginx
    container_name: cms-webserver
    working_dir: /application
    depends_on:
      - app
    links:
      - app
    volumes:
      - ./public:/var/www/html/public
      - ./storage/logs/nginx/:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:80'
    networks:
      - cms-web_default

  redis:
    image: redis:alpine
    container_name: cms-redis
    ports:
      - 6380:6379
    networks:
      - cms-web_default

networks:
  cms-web_default:
    external: true
